### ISSUE TITLE
Regenerate the docs

### ISSUE THREAD

**Issue by daaku** [budu/lobos#17]
There's so much more goodness in the library than the current version of the generated docs show. You should regenerate them :)

**Comment by budu** [comment]
I've done it, but there's appear to have been some nasty regressions to Marginalia. The rest of the website would need some more work, but I think I'll just drop the current approach and use [Stasis](https://github.com/winton/stasis) to generate a website from the readme.md file.

I'll leave this issue open to push me to put in more work into this project.

**Comment by daaku** [comment]
Thanks, appreciate it. On an unrelated note, lobos was the only library between it, clojureql and korma that handled delimited identifiers correctly -- kudos on that :)

**Comment by budu** [comment]
Yeah, that "little detail" can be a big problem in some (edge) case, I
ended up doing supporting delimited identifiers to be able to test Lobos
code across databases that behaved differently (some upcase others downcase
unquoted identifiers) and in the end it forced me to write my own
(extremely simple) query helpers to write more complex tests as ClojureQL
didn't support them.

I tried to add support to ClojureQL, but given but due to how "complected"
the compiler was. Later, I kickstarted the delimited identifier work in
java.jdbc and I'm quite pleased with what Sean has done with it although I
still use my own custom code in Lobos.

I'll probably take a shot at adding that feature to Korma as the code seem
easier to work with than CQL at some point in the future. Still, ibdknox is
so productive, he might do it himself before I get onto it!

Slowly but surely, Clojure support for SQL is getting awesome!

On Sun, Nov 13, 2011 at 12:03 PM, Naitik Shah <
reply@reply.github.com

**Comment by daaku** [comment]
I found my way here: http://clojure.github.com/java.jdbc/doc/clojure/java/jdbc/NameMapping.html -- would be nice if korma and clojureql respected this. I'm still a clojure n00b, but I'm enjoying using SQL here more than I thought I would :)

**Comment by budu** [comment]
I finally got Marginalia to work properly under Clojure 1.3, the annotated code has been updated.

**Comment by daaku** [comment]
Thanks!
