### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by ghost** [budu/lobos#25]
I get "java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number" when I'm calling `migrate` or `rollback`.
Here is the full stacktrace: https://gist.github.com/1505863
Here is the code: https://gist.github.com/53121263ddee84868545
Note that direct calls to (create ...) and (drop ...) works fine.

**Comment by budu** [comment]
I just had a quick look at it and it seems related to a bug in the schema analyzer. It currently try to read the whole schema even though Lobos only need the schema (or the database in MySQL) name, I'll try to fix this tonight.

**Comment by budu** [comment]
I was totally wrong in my first look at this bug, it ended up being a quite hard one to find! It was showing itself only during migration because the migration commands need to inspect the database schema to see if the `lobos_migrations` table is already there. Currently the analyzer try to get the full table definition and it appears there's an issue with the recent MySQL drivers where their DatabaseMetaData implementation doesn't follow the standard and return an string instead of an integer for the index type, so it was failing while trying to read the surrogate key index. Funny, isn't it?

Anyway, I've made a quick fix and will report that issue to MySQL. A new snapshot has been released and it should _hopefully_ work on your side too.

**Comment by budu** [comment]
While filling the bug report, I just realized that the driver version you're using is actually quite old and the driver I was using for testing is much more recent. It appear that bug has already been fixed (see below), I'll leave my fix there in case some people need to use the old versions for some reason, but this will get deprecated at some point.

http://bugs.mysql.com/bug.php?id=44869

**Comment by ghost** [comment]
Thank you for such a quick fix! I was using older driver because there was some problems with more recent drivers and clojureql, although, ther are already fixed in the newer versions of clojureql, but anyway, as you've said someone can still rely on it.

But there is another problem now: when I'm calling `migrate` or `rollback` nothing happens. No exception is thrown, nil is returned, but no changes made in database. I've tried it with the same code I've posted above, with both 5.1.6 and 5.1.18 versions of mysql connector. Direct calls still work. Ideas? Do you want me to create a new issue for that?

Also, I've noticed that subsequent calls to `defmigration` causes `migrations` to grow, so while developing interactively duplicating migrations are accumulating. I don't know whether it can cause some problems, but maybe it makes sense to make `migrations` a set?

**Comment by budu** [comment]
That might be caused by the structure of your project and that you must have reloaded the migrations namespace manually. You better follow the readme and create a namespace called `lobos.migrations`, this will (as of today) be automatically loaded when you issue a migration command. So the overall process might look like:
- create a migrations file
- open a repl
- load lobos.core: `(use 'lobos.core)`
- issue some migration commands: `(migrate)`
- edit your migrations file
- issue some other migration commands...

Sorry for the late reply!

**Comment by ghost** [comment]
I'll try it, thank you!
