### ISSUE TITLE
Columns are created in funny order when creating a table

### ISSUE THREAD

**Issue by jsyrjala** [budu/lobos#29]
```
(defmigration add-event-annotations-table
  (up [] (create
          (tbl :event_annotations
                    (refer-to :events)
                    (varchar :annotation 256))))
  (down [] (drop (table :event_annotations))))
```

Results in this with PostgreSQL:

```
CREATE TABLE event_annotations (
    annotation character varying(256),
    event_id integer NOT NULL,
    id integer NOT NULL,
    created_on timestamp without time zone DEFAULT now(),
    updated_on timestamp without time zone
 );
```

Natural order for fields is: id, event_id, annotation, updated_on, created_on.

**Comment by budu** [comment]
Good catch! I didn't thought about columns order when writing that example. As tables use a PersistentArrayMap to store columns and the column functions `conj` the added columns, their order is reversed. The `table` function thus reverse the given elements so that they're add in the right order. Here's an updated macro that should respect the more natural order of columns:

``` clojure
(defmacro tbl [name & elements]
  `(-> (table ~name)
       (timestamps)
       ~@(reverse elements)
       (surrogate-key)))
```

As you see everything must be reversed and the elements inserted between the surrogate key and the timestamps. I'll update the readme to use this example.
