### ISSUE TITLE
alter :modify for column re-sizing isn't working

### ISSUE THREAD

**Issue by techwhizbang** [budu/lobos#38]
I can't seem to get the alter :modify to work, there doesn't seem to be a good example in the doc string nor the test suite covering this. I am using MySQL mysql/mysql-connector-java "5.1.8"

See my gist 
https://gist.github.com/2008998

**Comment by budu** [comment]
Yes, that's an unfortunate limitation of Lobos that can't be easily fixed until version 1.1. That's mainly because of MySQL which have a weird `ALTER` syntax where we must give the full column definition and with the currently limited support for parsing `DEFAULT` expressions I decided to postpone that feature. If you have any ideas concerning this problem I would be glad to hear them.

**Comment by budu** [comment]
After thinking about I think I'll do something for version 1.0 as this is quite a big limitation, I'll see what I can do tomorrow.

**Comment by techwhizbang** [comment]
That sounds excellent and it is appreciated! The MySQL ALTER syntax is pretty important and is preventing me from porting our home grown migration strategy over to lobos.

**Comment by budu** [comment]
I've just pushed a new snapshot with support for changing data type (and options like NOT NULL) to clojars. It only support H2 and MySQL for now. I hadn't had time to write documentation for it, but it should have the same behavior as H2, so you don't have to specify all the column options, default clause will get dropped if the datatype has changed though. I suggest you experiment with it to get how it work until I work out the details and add support for other DBs. So beware this is a alpha feature, backup your DB before using it!

**Comment by techwhizbang** [comment]
Just wanted to drop you line and let you know this fixed worked for us, and is in production now. We look forward to v1.1, thanks again!
