### ISSUE TITLE
exception while creating unique-constraint

### ISSUE THREAD

**Issue by artureg** [budu/lobos#40]
I try to create unique or primary key 

```
(create (table :userroles
             (integer :userid)
             (integer :roleid)))

 (unique :userroles [:userid])
```

but i got exception 

Caused by: java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.Associative
    at clojure.lang.RT.assoc(RT.java:664)
    at clojure.core$assoc.invoke(core.clj:170)
    at clojure.core$update_in.doInvoke(core.clj:4969)
    at clojure.lang.RestFn.invoke(RestFn.java:467)
    at lobos.schema$unique_constraint.invoke(schema.clj:237)

**Comment by budu** [comment]
The `unique` schema element takes a table as first argument, not a table name. So you'd need to do:

```
(unique (table :userroles)  [:userid])
```

Also, take note that this expression only define an index, it does not create it, so might want to enclose it inside a `create` statement.

I'll consider adding support for direct keyword, I don't see any problem that could cause and it should be a helpful shortcut.

**Comment by artureg** [comment]
It works, thanks. 
It would be great to added more informative examples in the documentation.

(lc/create (ls/table :userroles
                 (ls/integer :userid)
                 (ls/integer :roleid)
                 (ls/primary-key (ls/table :userroles)  [:userid :roleid])
                 (ls/unique (ls/table :userroles)  [:userid :roleid])
                 (ls/column :userid [:refer :users :id])
                 (ls/column :roleid [:refer :roles :id])
                 ))

**Comment by budu** [comment]
Yes, I'm still working on better documentation, but got it's going slowly because I'm busy with my job and other projects, sorry about that. I hope to get going in a week or two and release version 1.0 this spring with the new doc.

A note on your last code snippet, the reason why the `unique` and `primary-key` functions takes a table element instead of a name is to be used inside table expression without having to explicitly refer to the table, e.g.:

``` clojure
(create 
 (table :roles
   (integer :userid [:refer :users :id])
   (integer :roleid [:refer :roles :id])
   (primary-key [:userid :roleid]))
```

You can see here that `primary-key` is used in the same way as `integer`, the table element is automatically passed as the first argument to those, using the `->` expression threading macro behind the scene. Also, the column options can be included directly into their definition.

**Comment by artureg** [comment]
It is now clear.
Thank you for your work
